[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm watch"
  port = 3000

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31560000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "Content-Security-Policy" = "default-src 'self' https://inwavelabs.com https://www.inwavelabs.com https://cdn.usefathom.com;"
